{
 "title": "Vagrant Box",
 "description": "host monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU-0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "collectd.graph_host.cpu-0.*" }
   ]
  },
  {
   "title": "CPU-1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "collectd.graph_host.cpu-1.*" }
   ]
  },
  {
   "title": "CPU-2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "collectd.graph_host.cpu-2.*" }
   ]
  },
  {
   "title": "eth0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.graph_host.interface-eth0.*.*"
    }
   ]
  },
  {
   "title": "eth1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.graph_host.interface-eth1.*.*"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "collectd.graph_host.memory.*" }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "collectd.graph_host.disk-vda.*" }
   ]
  },
  {
   "title": "uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "collectd.graph_host.uptime.*" }
   ]
  },
  {
   "title": "connTrack",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "collectd.graph_host.conntrack.*"
    }
   ]
  }
 ]
}